import type { LayerConfig } from './types';

export const GEOJSON_BASE = '/data/cimento/dashboard-matriculas-medellin-fase1/geojson';

export const LAYER_CONFIGS: LayerConfig[] = [
  {
    id: 'poligono',
    label: 'Polígono Cimento',
    fileName: 'poligono.geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    color: '#a738cd',
    fillOpacity: 0.05,
  },
  {
    id: 'barrio_filtro',
    label: 'Barrios',
    fileName: 'barrio_filtro.geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    color: '#6366f1',
    fillOpacity: 0.15,
    cbmlField: 'codigo',
  },
  {
    id: 'estrato_filtro',
    label: 'Estrato',
    fileName: 'estrato_filtro.geojson',
    geometryType: 'polygon',
    defaultVisible: false,
    color: '#22c55e',
    fillOpacity: 0.2,
    cbmlField: 'codigo_bar',
  },
  {
    id: 'lotes_filtro',
    label: 'Lotes',
    fileName: 'lotes_filtro.geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    color: '#828DEE',
    fillOpacity: 0.25,
    cbmlField: 'cbml',
  },
  {
    id: 'construcciones_filtro',
    label: 'Construcciones',
    fileName: 'construcciones_filtro.geojson',
    geometryType: 'polygon',
    defaultVisible: true,
    color: '#f97316',
    fillOpacity: 0.35,
    cbmlField: 'cbml',
  },
  {
    id: 'nomenclatura_filtro',
    label: 'Nomenclatura',
    fileName: 'nomenclatura_filtro.geojson',
    geometryType: 'polygon',
    defaultVisible: false,
    color: '#06b6d4',
    fillOpacity: 0.2,
    cbmlField: 'cbml_left',
  },
  {
    id: 'usos_predio_filtro',
    label: 'Usos del predio',
    fileName: 'usos_predio_filtro.geojson',
    geometryType: 'point',
    defaultVisible: true,
    color: '#eab308',
    cbmlField: 'cbml',
  },
  {
    id: 'base_predios_completa',
    label: 'Matrículas',
    fileName: 'base_predios_completa.geojson',
    geometryType: 'point',
    defaultVisible: true,
    color: '#a738cd',
    cbmlField: 'cbml',
  },
];

export const DATA_LAYER_IDS = LAYER_CONFIGS.map((l) => l.id);
